service: zim-pepper-backend
runtime: java11
instance_class: F1
# look at tuning for spawning new VMs under load (10 connections -> new instance)

# set 2 min instances

manual_scaling:
  instances: 2

network:
  instance_tag: study-server # necessary for firewall rules so that DSM will accept https requests from pepper

# get size from env var, try this without mx, ms
entrypoint: java -Dddp.firecloudKeysDir=fc_keys -Dconfig.file=application.conf DataDonationPlatform.jar

skip_files:
  - src/main/resources/org/.*
  - src/main/resources/*.pdf
