service: zim-pepper-backend
runtime: java11
instance_class: F1
# look at tuning for spawning new VMs under load (10 connections -> new instance)

manual_scaling:
  instances: 2

network:
  instance_tag: study-server # necessary for firewall rules so that DSM will accept https requests from pepper

# will need to move all contents of tcell into deploy, and copy tcell_agent.config after rending
entrypoint: java -javaagent:tcell/tcellagent.jar-Dddp.firecloudKeysDir=fc_keys -Dconfig.file=application.conf DataDonationPlatform.jar

skip_files:
  - src/main/resources/org/.*
  - src/main/resources/*.pdf
