version: 2.1
references:
  maven_cache_key: &maven_cache_key
                   maven-deps-{{ checksum "parent-pom.xml" }}-{{ checksum "pom.xml" }}


executors:
  maven-executor:
    docker: # todo: create new image endpoint, add this in admin tab for faster starts
      - image: broadinstitute/pepper-angular-toolkit:backend_build_v1
    working_directory: ~/repo

commands:
  render-configs:
    - run:
        name: <<parameters.study_key>> determine deployment environment
        command: |
          case "<< pipeline.git.branch >>" in
          develop)
            DEPLOY_ENV=dev
          ;;
            study-server-to-appengine)
            DEPLOY_ENV=dev
          ;;
          test)
            DEPLOY_ENV=test
            NG_BUILD_OPTS=--prod --aot
          ;;
          staging)
            DEPLOY_ENV=staging
            NG_BUILD_OPTS=--prod --aot
          ;;
          staging)
            DEPLOY_ENV=prod
            NG_BUILD_OPTS=--prod --aot
          ;;
          *)
            echo "Cannot map << pipeline.git.branch >> to a deployment environment"
            exit 17
          ;;
          esac
          echo "Setting deployment ENVIRONMENT to $DEPLOY_ENV"
          echo "export ENVIRONMENT=$DEPLOY_ENV" >> $BASH_ENV
          source $BASH_ENV
    - run:
        name: show environment variables
        command: env
    - run:
        name: api-build.sh
        command: ./api-build.sh v1 $ENVIRONMENT . --config
        environment:
          USE_DOCKER: false


  install-maven-dependencies:
    description: "Install maven dependencies"
    parameters:
      study_key:
        type: string
      study_guid:
        type: string
    steps:
      - checkout:
          path: ~/repo
      - run:
          name: <<parameters.study_key>> show pipeline vars
          command: |
            echo "pipeline.id << pipeline.id >>"
            echo "pipeline.number	 << pipeline.number	 >>"
            echo "pipeline.project.git_url << pipeline.project.git_url >>"
            echo "pipeline.project.type << pipeline.project.type >>"
            echo "pipeline.git.tag << pipeline.git.tag >>"
            echo "pipeline.git.branch << pipeline.git.branch >>"
            echo "pipeline.git.revision << pipeline.git.revision >>"
            echo "pipeline.git.base_revision << pipeline.git.base_revision >>"
      - restore_cache:
          key: *maven_cache_key
      - run:
          name: fetch maven dependencies
          command: |
            mvn --batch-mode --fail-never -file smoketest-pom.xml clean install package test
            mvn --batch-mode --fail-never -file housekeeping.xml clean install package test
            mvn --batch-mode --fail-never -file pom.xml clean install package test
          working_directory: ~/repo
      - save_cache:
          key: *maven_cache_key
          paths:
            - ~/.m2


jobs:
  maven-install:
    executor:
      name: maven-executor
    steps:
      - install-maven-dependencies

workflows:
  version: 2
  build-deploy:
    jobs:
      - maven-install:
          filters:
            branches:
              only: study-server-to-appengine
