version: 3

extends: https://api.github.com/repos/example/pullapprove-config/contents/.pullapprove.yml

notifications:
  - when: pull_request.opened
    comment: |
      Hey @{{ author }}, it looks like we're doing a deploy to @{{base}}.  Cool!
      The reviewers will let you know when it's approved.
  - when: pullapprove.approved	 
    comment: |
      Thanks @{{ author }}, your @{{base}} deployment has been approved.  Please follow the merge instructions.

groups:
  test-deployment:
    conditions:
    - "base.ref == 'pullapprove_poc'"
    reviews:
      required: 1
    reviewers:
      users:
      - zyme
      - yufengwng	