version: 2

notifications:
  - when: pull_request.opened
    if: "base.ref == 'test' or base.ref == 'staging' or base.ref == 'production'"
    comment: |
      Hey @{{ author }}, looks like we're doing a deploy to @{{base}}.  Cool!
      The reviewers will let you know when it's approved.
  - when: pullapprove.approved
    if: "base.ref == 'test' or base.ref == 'staging' or base.ref == 'production'"
    comment: |
      Thanks @{{ author }}, your @{{base}} deployment has been approved.  Please follow the merge instructions.

groups:
  test-deployment:
    required: 2
    users:
      - zyme
      - yufengwng

    conditions:
    - "base.ref == 'test'"
