version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: broadinstitute/study-server-build:2020-04-30A
    steps:
      - checkout
      - run: echo "this is the build job"
      - run: echo "Go an echo parameter called << pipeline.parameters.project >>"

parameters:
  project:
    type: enum
    enum: ["dss", "dsm","api-docs", "nothing"]
    default: "dss"

# Orchestrate our job run sequence
workflows:
  build_and_test:
    when:
      equal: ["api-docs", << pipeline.parameters.project >>]
    jobs:
      - build


