version: 2.1

# Define the jobs we want to run for this project
jobs:
  build:
    docker:
      - image: broadinstitute/study-server-build:2020-04-30A
    steps:
      - checkout
      - run: echo "this is the build job"
      - run: echo "Go an echo parameter called << pipeline.parameters.project >>


# Orchestrate our job run sequence
workflows:
  build_and_test:
    jobs:
      - build
