version: "3.9"
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_USER: pepper
      MYSQL_PASSWORD: pepper-dev
      MYSQL_ROOT_PASSWORD: pepper-dev
      TZ: "Etc/UTC"
    volumes:
      - "$PWD/data/mysql:/var/lib/mysql"
      - "$PWD/conf/mysql/my.cnf:/opt/mysql/my.cnf"
      - "$PWD/log/mysql:/var/log/mysql"
      - "$PWD/conf/mysql/initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306
    command: ["mysqld", "--defaults-extra-file=/opt/mysql/my.cnf"]
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: [
      "redis-server",
      "/etc/redis/redis.conf"
    ]
    volumes:
      - "$PWD/conf/redis:/etc/redis/"
      - "$PWD/data/redis:/data/"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.3.3
    environment:
      node.name: ddp-es-node
      discovery.type: single-node
      cluster.name: ddp-es-cluster
      bootstrap.memory_lock: true
      ES_JAVA_OPTS: "-Xms1024m -Xmx1024m"
      logger.level: warn
      xpack.security.enabled: false
      xpack.security.enrollment.enabled: false
      xpack.security.http.ssl.enabled: false
      xpack.security.transport.ssl.enabled: false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - es-net
    volumes:
      - "$PWD/data/elasticsearch:/usr/share/elasticsearch/data"
    ports:
      - "9200:9200"
      - "9300:9300"
  kibana:
    image: docker.elastic.co/kibana/kibana:8.3.3
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      XPACK_ENCRYPTEDSAVEDOBJECTS_ENCRYPTIONKEY: 0123456789abcdeffedcba9876543210
      XPACK_REPORTING_ENCRYPTIONKEY: 0123456789abcdeffedcba9876543210
      XPACK_SECURITY_ENCRYPTIONKEY: 0123456789abcdeffedcba9876543210
    volumes:
      - "$PWD/data/kibana:/usr/share/kibana/data"
    ports:
      - "5601:5601"
    networks:
      - es-net
networks:
  es-net: